### PR TITLE
Eager Load relations. Sync cart info.

### PR DESCRIPTION
**Pull request by rrpadilla**
This PR adds a method to **contentWithRelations** and the **HasRelationsTrait** class. Using this method we can eager load relations.
The **contentWithRelations** method accepts a Closure, that way you can eager load relation and customize the query to get the models.
This method will sync cart info, like price, name, etc.

**IMPORTANT**: Everytime you call $cartItem->model it hit database query each time. So you should use the this solution instead.

Fixes:
- #112
- #92

## Controller:

```php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Gloudemans\Shoppingcart\Cart;
use Illuminate\Http\Request;

class CartController extends Controller
{
    protected Cart $cart;

    public function __construct(Cart $cart)
    {
        $this->cart = $cart;
    }

    public function index(Request $request)
    {
        $cartContent = $this->cart->contentWithRelations(function ($ids) {
            return Product::with('image')
                ->whereIn('id', $ids)
                ->get();
        });

        return view('cart.index', [
            'cart' => $this->cart,
            'cartContent' => $cartContent,
        ]);
    }
}
```

## View

```blade
@foreach($cartContent as $cartItem)
     @include('cart._item', ['product' => $cart->getRelation($cartItem->rowId)])
@endforeach
```

### CODE REVIEW

**Comment by bumbummen99** [comment]
Looks good to me, tought why does it need a new save() method (there already is store)?

**Comment by rrpadilla** [comment]
@bumbummen99 because the current store method will return an error if there is a cart already saved. The new save method is to keep the current store function to avoid breaking change. The new save method will update or insert the cart, is using updateOrInsert.

**Comment by bumbummen99** [comment]
@rrpadilla But does it not make sense to just remove the old method and create a new major release? I might be overlooking something as i have not used it in a while but i think that would be perfectly fine given we allow to check if a cart is already stored if someone expects that exception being thrown. If it does not make sense what i am saying then i am fine with having two methods but i fear that it will create confusion.

**Comment by rrpadilla** [comment]
@bumbummen99 That's why I added the new **save** method. Just in case someone wants to keep the old behavior expecting an exception.

**Comment by aneeskhan47** [comment]
is this pr still active? and can it be merged?

**Comment by bumbummen99** [comment]
> 
> 
> is this pr still active? and can it be merged?
> 
> @rrpadilla @bumbummen99

Sorry, i am currently moving. I think it can be merged, but tests have to be fixed first. Also i would rather have an option to throw if a cart already exists and deprecate/extend the old one instead of having multiple save/store methods if that is possible.

**Comment by nocodelab** [comment]
Any update on this one?
This will improve the cart performances drastically :)

**Comment by bumbummen99** [comment]
https://github.com/bumbummen99/LaravelShoppingcart#attention

**Pull request closed without merging**
