### PR TITLE
Added erase() test and new exception instead of just returning nothing

### PR DESCRIPTION
**Pull request by nexxai**
Fixes https://github.com/bumbummen99/LaravelShoppingcart/issues/57

### CODE REVIEW

**Comment by nexxai** [comment]
I don't understand why StyleCI is choking; the before and after text both look the same.

**Comment by SharakPL** [comment]
You're using tabs instead of spaces. That's against PSR standards.

**Comment by nexxai** [comment]
Also, this will be a breaking change.  If people attempt to restore a non-existent cart, they may be expecting it to just return nothing, rather than an exception.  I'll fix this up right now and get it submitted.

**Comment by nexxai** [comment]
@SharakPL Can you review my .php_cs and let me know which setting I should be changing to be PSR-compliant? 

https://gist.github.com/nexxai/40388d76e88ac07cbf08e80c4d645d4c

**Comment by bumbummen99** [comment]
@nexxai According to https://stackoverflow.com/questions/37193540/configure-php-cs-fixer-indentation-for-2-spaces-rather-than-4 you should simply replace the `\t` in your config with spaces

**Comment by nexxai** [comment]
Cancelling; resubmitting.

**Comment by SharakPL** [comment]
I recommend using [PSR12](https://www.php-fig.org/psr/psr-12/). Just make it your default with `phpcs --config-set default_standard PSR12`.

**Pull request closed without merging**
