### PR TITLE
Upgrade/laravel 10

### PR DESCRIPTION
**Pull request by anayarojo**
# What's new

- Added Laravel 10 compatibility.
- Added PHP 8.0 to GitHub Actions tests.
- Fixed rounding bug in unit tests.

image

Please let me know your comments, questions, or concerns.

### CODE REVIEW

**Comment by trippo** [comment]
@bumbummen99 please merge it

**Comment by anayarojo** [comment]
Hi @trippo, meanwhile this PR is approved you can use my fork library
https://packagist.org/packages/anayarojo/shoppingcart

```
"anayarojo/shoppingcart": "^4.2.1"
```

**Comment by bumbummen99** [comment]
https://github.com/bumbummen99/LaravelShoppingcart#attention

**Comment by trippo** [comment]
Thanks @bumbummen99 for your work

**Pull request closed without merging**
