### PR TITLE
Deprecate session, use database instead

### PR DESCRIPTION
**Pull request by bumbummen99**
Instead of storing CartItems in the session we should store them in the database instead. While this does put more load on the database, it will allow for a far better implementation in regards to API usage (there is no session). Also it will allow us to use the power of Eloquent.

ToDo:
- [ ] Store CartItems in the database
- [ ] Optimize queries
- [ ] Cache what can be cached

### CODE REVIEW

**Comment by vanthao03596** [comment]
Great feature, Can we remove price field ? I think in realworld app prices change frequently, we can get price from CanBeBougth item

**Comment by JieAnthony** [comment]
Hi, can this PR be merged?

**Comment by bumbummen99** [comment]
> Hi, can this PR be merged?

Not really, i guess all i did was to yeet the session and create models but no logic for save/load of the models. I appreciate any help, just PR into the PR.

**Comment by bumbummen99** [comment]
https://github.com/bumbummen99/LaravelShoppingcart#attention

**Pull request closed without merging**
